// =====================================================
// Products Page Main JS
// Data comes from data/js/*.js generated by build.py.
// =====================================================

document.addEventListener("DOMContentLoaded", () => {
    const productPage = document.querySelector(".product-page");
    const categoryMenu = document.getElementById("categoryMenu");
    const productList = document.getElementById("productList");
    const searchInput = document.getElementById("searchInput");
    const searchButton = document.getElementById("searchButton");
    const clearSearch = document.getElementById("clearSearch");
    const searchResultInfo = document.getElementById("searchResultInfo");
    const recentProductNotice = document.getElementById("recentProductNotice");
    const mobileCategoryToggle = document.getElementById("mobileCategoryToggle");
    const mobileCategoryArrow = document.getElementById("mobileCategoryArrow");
    const mobileCategoryText = document.getElementById("mobileCategoryText");

    let currentCategoryIds = null;

    const escapeHtml = text => String(text ?? "")
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");

    const setMobileCategoryName = name => {
        if (mobileCategoryText) mobileCategoryText.textContent = name || siteText.products.categories;
    };

    const getRecentProduct = () => {
        const raw = sessionStorage.getItem("recentProduct");
        if (!raw) return null;
        try { return JSON.parse(raw); }
        catch (_) { sessionStorage.removeItem("recentProduct"); return null; }
    };

    const saveRecentProduct = product => {
        sessionStorage.setItem("recentProduct", JSON.stringify({
            model: product.model || "",
            name: getLocalizedProduct(product).name || product.name || "",
            url: new URL(window.location.href).href,
            scrollY: window.scrollY
        }));
    };

    const getCategoryChildren = category => Array.isArray(category?.children) ? category.children : [];

    // Includes the selected category and every descendant. This is required so that
    // clicking a parent category shows all products assigned anywhere below it.
    const getDescendantIds = category => [category.id, ...getCategoryChildren(category).flatMap(getDescendantIds)];

    const findCategoryById = (list, id) => {
        for (const category of list) {
            if (String(category.id) === String(id)) return category;
            const found = findCategoryById(getCategoryChildren(category), id);
            if (found) return found;
        }
        return null;
    };

    const getCategoryPath = (categoryId, lang = "en") => {
        const path = [];
        let current = findCategoryById(categories, categoryId);
        while (current) {
            path.unshift(getLocalizedCategoryNameForLang(current, lang));
            if (!current.parentId || String(current.parentId) === "0") break;
            current = findCategoryById(categories, current.parentId);
        }
        return path;
    };

    const getLocalizedCategoryNameForLang = (category, lang) =>
        category?.translations?.[lang] || category?.translations?.en || category?.name || "";

    const setActiveAllProducts = () => {
        document.querySelectorAll(".category-node").forEach(node => node.classList.remove("active-category"));
        document.querySelector(".all-products-item")?.classList.add("active-all-products");
    };

    const setActiveCategory = element => {
        document.querySelectorAll(".category-node").forEach(node => node.classList.remove("active-category"));
        document.querySelector(".all-products-item")?.classList.remove("active-all-products");
        element?.classList.add("active-category");

        let parent = element?.parentElement;
        while (parent && parent !== categoryMenu) {
            if (parent.classList?.contains("category-node")) {
                parent.classList.remove("collapsed");
                const arrow = parent.querySelector(":scope > .category-row .category-arrow");
                if (arrow && arrow.tagName === "BUTTON") arrow.textContent = "⌄";
            }
            parent = parent.parentElement;
        }
    };

    const renderRecentProduct = () => {
        if (!recentProductNotice) return;
        const recent = getRecentProduct();
        if (!recent) {
            recentProductNotice.innerHTML = "";
            return;
        }
        recentProductNotice.innerHTML = `<div class="recent-product-inner"><span>${escapeHtml(siteText.products.recentlyViewed)}:</span><strong>${escapeHtml(recent.model || "")}</strong></div>`;
    };

    const matchesProduct = (product, terms) => {
        const fields = [
            product.model,
            product.translations?.en?.name, product.translations?.fr?.name, product.translations?.es?.name,
            product.translations?.en?.description, product.translations?.fr?.description, product.translations?.es?.description,
            ...(product.specifications || []).flatMap(spec => [
                spec.name?.en, spec.name?.fr, spec.name?.es,
                spec.value?.en, spec.value?.fr, spec.value?.es
            ]),
            ...(product.categoryPath?.en || []),
            ...(product.categoryPath?.fr || []),
            ...(product.categoryPath?.es || [])
        ];
        const searchable = fields.filter(Boolean).join(" ").toLowerCase();
        return terms.every(term => searchable.includes(term));
    };

    const sortProducts = list => [...list].sort((a, b) => {
        if (Boolean(a.new) !== Boolean(b.new)) return a.new ? -1 : 1;
        return (a.rowOrder || 0) - (b.rowOrder || 0);
    });

    const renderProducts = list => {
        if (!productList) return;
        productList.innerHTML = "";
        const recent = getRecentProduct();
        const sorted = sortProducts(list);

        if (!sorted.length) {
            productList.innerHTML = `<div class="no-products"><h3>${escapeHtml(siteText.products.noProducts)}</h3><p>${escapeHtml(siteText.products.noProductsText)}</p></div>`;
            return;
        }

        sorted.forEach(item => {
            const localized = getLocalizedProduct(item);
            const card = document.createElement("div");
            card.className = "product-card";
            if (recent?.model && recent.model === item.model) card.classList.add("recent-product-card");

            const images = Array.isArray(item.images) && item.images.length ? item.images : [siteImages.warning];
            const primaryImage = images[0];
            const hoverImage = images[1] || images[0];
            const isNew = Boolean(item.new);

            card.innerHTML = `
                <div class="product-card-image">
                    <img class="product-image product-image-primary" src="${escapeHtml(primaryImage)}" alt="${escapeHtml(localized.name)}" loading="lazy" decoding="async">
                    <img class="product-image product-image-hover" src="${escapeHtml(hoverImage)}" alt="" loading="lazy" decoding="async">
                </div>
                <h3 class="product-title">${escapeHtml(localized.name)}</h3>
                <div class="product-model">Model: ${escapeHtml(item.model)}</div>
                <p class="product-description">${escapeHtml(localized.description)}</p>
                <a href="detail.html?model=${encodeURIComponent(item.model)}">${escapeHtml(siteText.products.viewDetails)}</a>
            `;

            if (isNew) {
                const badge = document.createElement("span");
                badge.className = "new-product-badge";
                badge.textContent = "NEW";
                card.prepend(badge);
            }

            const openDetail = event => {
                if (event) event.stopPropagation();
                saveRecentProduct(item);
                window.location.href = `detail.html?model=${encodeURIComponent(item.model)}`;
            };

            card.addEventListener("click", openDetail);
            card.querySelector("a")?.addEventListener("click", openDetail);
            productList.appendChild(card);
        });
    };

    const showAllProducts = () => {
        currentCategoryIds = null;
        renderProducts(products);
    };

    const showProductsByCategoryIds = ids => {
        const idSet = new Set(ids.map(String));
        currentCategoryIds = [...new Set(ids.map(String))];
        renderProducts(products.filter(product => idSet.has(String(product.categoryId))));
    };

    const updateSearchInfo = (keyword = "", count = null) => {
        if (!searchResultInfo) return;
        if (!keyword) { searchResultInfo.textContent = ""; return; }
        if (count === 0) {
            searchResultInfo.textContent = siteText.products.noSearchResults;
            return;
        }
        const found = count === 1 ? siteText.products.productFound : siteText.products.productsFound;
        searchResultInfo.textContent = `${count} ${found} ${siteText.products.searchFor} "${keyword}"`;
    };

    const searchProducts = (suppliedKeyword = null, updateUrl = true) => {
        const keyword = String(suppliedKeyword !== null ? suppliedKeyword : (searchInput?.value || "")).trim().toLowerCase();
        if (searchInput && suppliedKeyword !== null) searchInput.value = suppliedKeyword;

        if (!keyword) {
            currentCategoryIds?.length ? showProductsByCategoryIds(currentCategoryIds) : showAllProducts();
            updateSearchInfo();
            if (updateUrl) {
                const url = new URL(window.location.href);
                url.searchParams.delete("search");
                window.history.replaceState({}, "", url);
            }
            return;
        }

        const terms = keyword.split(/\s+/).filter(Boolean);
        const source = currentCategoryIds?.length
            ? products.filter(product => new Set(currentCategoryIds.map(String)).has(String(product.categoryId)))
            : products;
        const result = source.filter(product => matchesProduct(product, terms));
        renderProducts(result);
        updateSearchInfo(keyword, result.length);

        if (updateUrl) {
            const url = new URL(window.location.href);
            url.searchParams.set("search", keyword);
            window.history.replaceState({}, "", url);
        }
    };

    const createCategoryElement = (category, level) => {
        if (!category.active) return document.createDocumentFragment();

        const wrapper = document.createElement("div");
        wrapper.className = `category-node category-level-${level}`;
        wrapper.dataset.categoryId = String(category.id);

        const row = document.createElement("div");
        row.className = "category-row";

        const childrenList = getCategoryChildren(category).filter(child => child.active);
        let arrow;
        if (childrenList.length) {
            arrow = document.createElement("button");
            arrow.type = "button";
            arrow.className = "category-arrow";
            arrow.textContent = "⌄";
        } else {
            arrow = document.createElement("span");
            arrow.className = "category-arrow-placeholder";
        }

        const title = document.createElement("div");
        title.className = "category-title";
        title.textContent = getLocalizedCategoryName(category);
        title.addEventListener("click", () => {
            const ids = getDescendantIds(category);
            if (searchInput) searchInput.value = "";
            showProductsByCategoryIds(ids);
            setActiveCategory(wrapper);
            setMobileCategoryName(getLocalizedCategoryName(category));
            updateSearchInfo();
            const url = new URL(window.location.href);
            url.searchParams.set("category", category.id);
            url.searchParams.delete("search");
            window.history.replaceState({}, "", url);
            if (window.innerWidth <= 768 && categoryMenu) {
                categoryMenu.classList.remove("mobile-category-open");
                mobileCategoryToggle?.classList.remove("active");
                if (mobileCategoryArrow) mobileCategoryArrow.textContent = "⌄";
            }
        });

        row.append(arrow, title);
        wrapper.appendChild(row);

        if (childrenList.length) {
            const children = document.createElement("div");
            children.className = "category-children";
            childrenList.forEach(child => children.appendChild(createCategoryElement(child, level + 1)));
            wrapper.appendChild(children);
            arrow.addEventListener("click", event => {
                event.preventDefault();
                event.stopPropagation();
                const collapsed = wrapper.classList.toggle("collapsed");
                arrow.textContent = collapsed ? "›" : "⌄";
            });
        }

        return wrapper;
    };

    const createCategoryMenu = () => {
        if (!categoryMenu) return;
        categoryMenu.innerHTML = "";
        const all = document.createElement("div");
        all.className = "all-products-item";
        all.innerHTML = `<div class="all-products-title">${escapeHtml(siteText.products.allProducts)}</div>`;
        all.querySelector(".all-products-title").addEventListener("click", () => {
            currentCategoryIds = null;
            if (searchInput) searchInput.value = "";
            showAllProducts();
            setActiveAllProducts();
            setMobileCategoryName(siteText.products.allProducts);
            updateSearchInfo();
            const url = new URL(window.location.href);
            url.searchParams.delete("category");
            url.searchParams.delete("search");
            window.history.replaceState({}, "", url);
            if (window.innerWidth <= 768) {
                categoryMenu.classList.remove("mobile-category-open");
                mobileCategoryToggle?.classList.remove("active");
                if (mobileCategoryArrow) mobileCategoryArrow.textContent = "⌄";
            }
        });
        categoryMenu.appendChild(all);
        categories.filter(category => category.active).forEach(category => categoryMenu.appendChild(createCategoryElement(category, 0)));
    };

    if (mobileCategoryToggle && categoryMenu) {
        mobileCategoryToggle.addEventListener("click", () => {
            const opened = categoryMenu.classList.toggle("mobile-category-open");
            mobileCategoryToggle.classList.toggle("active", opened);
            if (mobileCategoryArrow) mobileCategoryArrow.textContent = opened ? "⌃" : "⌄";
        });
    }
    if (searchButton) searchButton.addEventListener("click", () => searchProducts());
    if (searchInput) searchInput.addEventListener("keydown", event => {
        if (event.key === "Enter") searchProducts();
        if (searchInput.value.trim() === "") searchProducts("", true);
    });
    if (clearSearch) clearSearch.addEventListener("click", () => {
        if (searchInput) searchInput.value = "";
        searchProducts("", true);
        searchInput?.focus();
    });

    createCategoryMenu();
    renderRecentProduct();

    const params = new URLSearchParams(window.location.search);
    const categoryId = params.get("category");
    const savedSearch = params.get("search");

    if (categoryId) {
        const category = findCategoryById(categories, categoryId);
        if (category) {
            currentCategoryIds = getDescendantIds(category).map(String);
            showProductsByCategoryIds(currentCategoryIds);
            const node = [...document.querySelectorAll(".category-node")].find(el => el.dataset.categoryId === String(category.id));
            if (node) setActiveCategory(node);
            setMobileCategoryName(getLocalizedCategoryName(category));
        } else {
            showAllProducts();
            setActiveAllProducts();
            setMobileCategoryName(siteText.products.allProducts);
        }
    } else {
        showAllProducts();
        setActiveAllProducts();
        setMobileCategoryName(siteText.products.categories);
    }

    if (savedSearch) searchProducts(savedSearch, false);

    const recent = getRecentProduct();
    if (recent && recent.url === window.location.href) {
        setTimeout(() => window.scrollTo(0, recent.scrollY || 0), 80);
    }

    requestAnimationFrame(() => requestAnimationFrame(() => productPage?.classList.add("page-ready")));
});
